/* Copy this file over ../config.js to start a 60th birthday invitation. */
window.INVITATION_CONFIG = {
  eventType: "birthday",
  guestName: "Dear Juan and Family",
  enableOpeningScreen: true,
  openingTitle: "You are warmly invited",
  wedding: {},
  birthday: {
    names: "Maria's 60th Birthday",
    mainTitle: "Sixty Years of Love, Strength, and Beautiful Memories",
    subtitle: "Join us as we celebrate six wonderful decades of her life.",
    introMessage: "We gather to honor Maria's love, sacrifice, strength, laughter, and the beautiful memories she has given to family and friends.",
    fullStory: "<p>Maria's story is one of devotion, resilience, and quiet grace.</p>",
    storyTimeline: [{ year: "1966", text: "A beautiful life begins." }, { year: "2026", text: "Sixty years of memories." }],
    dressCode: "Elegant black, cream, gold, or warm neutral attire",
    theme: { primaryColor: "#fff7e8", secondaryColor: "#11100e", accentColor: "#c89a3c", textColor: "#201a14", backgroundColor: "#f8f1e4", headingFont: "'Cormorant Garamond', Georgia, serif", bodyFont: "'Inter', Arial, sans-serif", borderRadius: "6px", overlayOpacity: "0.52", sectionSpacing: "clamp(72px, 10vw, 132px)" },
    program: [{ time: "5:00 PM", title: "Guest Arrival" }, { time: "7:00 PM", title: "Tribute Video" }, { time: "8:00 PM", title: "Cake Ceremony" }],
    gift: { enabled: true, title: "Your Presence Is the Greatest Gift", message: "No gift is required.", details: "Optional charity, gift suggestions, or payment details go here." }
  },
  eventDate: "2026-12-18",
  startTime: "17:00",
  endTime: "22:00",
  timeZone: "Asia/Manila",
  passedMessage: "Thank you for celebrating with us.",
  venueName: "The Glass Garden",
  venueAddress: "257 Evangelista Ave, Pasig, Metro Manila",
  googleMapsLink: "https://maps.google.com/?q=The+Glass+Garden+Pasig",
  rsvpLink: "https://example.com/rsvp",
  rsvpDeadline: "2026-11-20",
  rsvpInstructions: "Kindly confirm your attendance before the RSVP deadline.",
  googleFormEmbedUrl: "",
  contactPerson: "Mia Reyes",
  contactNumber: "+63 900 000 0000",
  email: "hello@example.com",
  socialMediaLink: "https://facebook.com/",
  videoUrl: "",
  backgroundMusicUrl: "",
  footerMessage: "Thank you for being part of this meaningful celebration.",
  credit: "Invitation website created by Moumeants and Frames",
  images: { hero: "assets/images/birthday-hero.jpg", mobileHero: "assets/images/birthday-hero.jpg", background: "assets/images/texture.jpg", profile: "assets/images/birthday-hero.jpg", qrCode: "assets/qr/qr-placeholder.svg", heroPositionDesktop: "center center", heroPositionMobile: "center center", gallery: [{ src: "assets/images/birthday-hero.jpg", alt: "Warm milestone portrait", caption: "A life beautifully celebrated." }] },
  seo: { pageTitle: "Maria's 60th Birthday", description: "A premium cinematic birthday invitation.", ogTitle: "Maria's 60th Birthday", ogDescription: "Celebrate six wonderful decades with us.", ogImage: "assets/images/birthday-hero.jpg", themeColor: "#c89a3c" }
};
