/* Copy this file over ../config.js to start a wedding invitation. */
window.INVITATION_CONFIG = {
  eventType: "wedding",
  guestName: "Dear Juan and Family",
  enableOpeningScreen: true,
  openingTitle: "You are warmly invited",
  wedding: {
    names: "Daniel and Sophia",
    mainTitle: "Together, Always",
    subtitle: "We invite you to celebrate the beginning of our forever.",
    introMessage: "With grateful hearts, we invite you to witness a day shaped by love, family, and the promise of a life beautifully shared.",
    fullStory: "<p>Daniel and Sophia met in a season neither of them expected to become the beginning of forever.</p>",
    storyTimeline: [{ year: "2019", text: "First meeting." }, { year: "2026", text: "Wedding day." }],
    dressCode: "Formal / Champagne, black, ivory, or earth tones",
    theme: { primaryColor: "#f6efe4", secondaryColor: "#1c1712", accentColor: "#b48a4d", textColor: "#211c17", backgroundColor: "#fbf7f0", headingFont: "'Cormorant Garamond', Georgia, serif", bodyFont: "'Inter', Arial, sans-serif", borderRadius: "6px", overlayOpacity: "0.48", sectionSpacing: "clamp(72px, 10vw, 132px)" },
    program: [{ time: "3:00 PM", title: "Guest Arrival" }, { time: "4:00 PM", title: "Ceremony" }, { time: "6:30 PM", title: "Dinner" }],
    gift: { enabled: true, title: "Your Presence Is Our Gift", message: "For those who wish to give, details are available below.", details: "Gift registry and bank details go here." }
  },
  birthday: {},
  eventDate: "2026-12-18",
  startTime: "16:00",
  endTime: "22:00",
  timeZone: "Asia/Manila",
  passedMessage: "Thank you for celebrating with us.",
  venueName: "The Glass Garden",
  venueAddress: "257 Evangelista Ave, Pasig, Metro Manila",
  googleMapsLink: "https://maps.google.com/?q=The+Glass+Garden+Pasig",
  rsvpLink: "https://example.com/rsvp",
  rsvpDeadline: "2026-11-20",
  rsvpInstructions: "Kindly confirm your attendance before the RSVP deadline.",
  googleFormEmbedUrl: "",
  contactPerson: "Mia Reyes",
  contactNumber: "+63 900 000 0000",
  email: "hello@example.com",
  socialMediaLink: "https://facebook.com/",
  videoUrl: "",
  backgroundMusicUrl: "",
  footerMessage: "Thank you for being part of this meaningful celebration.",
  credit: "Invitation website created by Moumeants and Frames",
  images: { hero: "assets/images/wedding-hero.jpg", mobileHero: "assets/images/wedding-hero.jpg", background: "assets/images/texture.jpg", profile: "assets/images/wedding-gallery-1.jpg", qrCode: "assets/qr/qr-placeholder.svg", heroPositionDesktop: "center center", heroPositionMobile: "center center", gallery: [{ src: "assets/images/wedding-hero.jpg", alt: "Elegant couple portrait", caption: "A quiet frame of love." }] },
  seo: { pageTitle: "Daniel and Sophia | Together, Always", description: "A premium cinematic wedding invitation.", ogTitle: "Daniel and Sophia", ogDescription: "Celebrate the beginning of forever with us.", ogImage: "assets/images/wedding-hero.jpg", themeColor: "#b48a4d" }
};
